name: ci

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  NODE_VERSION: '14'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-20.04
    if: (!contains(github.ref, 'refs/heads/master') || contains(github.ref, 'refs/tags/v'))
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Lint JS
        run: yarn lint:js
      - name: Lint HBS
        run: yarn run prettier **/*.hbs -c
      - name: Run Tests
        run: yarn test:ember

  release:
    name: Release Package
    runs-on: ubuntu-20.04
    if: contains(github.ref, 'refs/tags/v')
    needs: [test]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy preview app
    runs-on: ubuntu-20.04
    needs: [test]
    if: ${{ github.ref == 'refs/heads/master' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Ember Build
        run: ./node_modules/ember-cli/bin/ember build --silent --environment=production
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
