name: ci

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  NODE_VERSION: 20
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-24.04
    if: (!contains(github.ref, 'refs/heads/master') || contains(github.ref, 'refs/tags/v'))
    timeout-minutes: 10
    steps:
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Lint JS
        run: pnpm lint:js
      - name: Lint HBS
        run: pnpm prettier **/*.hbs -c
      - name: Run Tests
        run: pnpm test:ember

  release:
    name: Release Package
    runs-on: ubuntu-24.04
    if: contains(github.ref, 'refs/tags/v')
    needs: [test]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Package Version
        id: pkg_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Trigger upfluence-web/deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: upfluence/upfluence-web
          ref: staging
          workflow: Bump Dependency
          token: ${{ secrets.PAT_TOKEN }}
          inputs: |
            {"package": "@upfluence/hypertable", "version": "^${{ steps.pkg_version.outputs.VERSION }}", "user": "${{ github.event.pusher.name }}"}

  deploy:
    name: Deploy preview app
    runs-on: ubuntu-24.04
    needs: [test]
    if: ${{ github.ref == 'refs/heads/master' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Ember Build
        run: pnpm ember build --silent --environment=production
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
